[project]
name = "llm"
version = "0.1.0"
description = "PyTorch learning project"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
]

[tool.setuptools]
py-modules = ["ch2", "net"]
